export const CURRIENCIES = {
  USD: { code: 'USD', name: 'US dollar' },
  EUR: { code: 'EUR', name: 'Euro' },
  JPY: { code: 'JPY', name: 'Japanese yen' },
  BGN: { code: 'BGN', name: 'Bulgarian lev' },
  CZK: { code: 'CZK', name: 'Czech koruna' },
  DKK: { code: 'DKK', name: 'Dutch krone' },
  GBP: { code: 'GBP', name: 'Pound sterling' },
  HUF: { code: 'HUF', name: 'Hungarian forint' },
  PLN: { code: 'PLN', name: 'Polish zloty' },
  RON: { code: 'RON', name: 'Romanian leu' },
  SEK: { code: 'SEK', name: 'Swedish krona' },
  CHF: { code: 'CHF', name: 'Swiss franc' },
  ISK: { code: 'ISK', name: 'Icelandic krona' },
  NOK: { code: 'NOK', name: 'Norwegian krone' },
  HRK: { code: 'HRK', name: 'Croatian kuna' },
  RUB: { code: 'RUB', name: 'Russian rouble' },
  TRY: { code: 'TRY', name: 'Turkish lira' },
  AUD: { code: 'AUD', name: 'Austrailian dollar' },
  BRL: { code: 'BRL', name: 'Brazilian real' },
  CAD: { code: 'CAD', name: 'Canadian dollar' },
  CNY: { code: 'CNY', name: 'Chinese yuan renminbi' },
  HKD: { code: 'HKD', name: 'Hong Kong dollar' },
  IDR: { code: 'IDR', name: 'Indonesian rupiah' },
  ILS: { code: 'ILS', name: 'Israeli shekel' },
  INR: { code: 'INR', name: 'Indian rupee' },
  KRW: { code: 'KRW', name: 'South Korean won' },
  MXN: { code: 'MXN', name: 'Mexican peso' },
  MYR: { code: 'MYR', name: 'Malaysian ringgit' },
  NZD: { code: 'NZD', name: 'New Zealand dollar' },
  PHP: { code: 'PHP', name: 'Philippine peso' },
  SGD: { code: 'SGD', name: 'Singapore dollar' },
  THB: { code: 'THB', name: 'Thai baht' },
  ZAR: { code: 'ZAR', name: 'South African rand' }
}